# Generated by Django 5.2 on 2025-04-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="license_number",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
