# Generated by Django 5.2 on 2025-04-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0003_alter_car_manufacturer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="license_number",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
